### ISSUE TITLE
Update team member names

### ISSUE THREAD

**Issue by ratnakar5938** [Bless-N-Bliss-NITR-chapter/Bless-n-Bliss#101]

**Comment by akash100000** [comment]
I want to work on this issue.

**Comment by deepakadda** [comment]
Hello I want to work with this issue

**Comment by ratnakar5938** [comment]
[Website_Names.xlsx](https://github.com/Bless-N-Bliss-NITR-chapter/Bless-n-Bliss/files/7486436/Website_Names.xlsx)

These r the names needed to be added

**Comment by ratnakar5938** [comment]
Also change the styling of the columns
